In [ ]:
# Import necessary libraries
import numpy as np
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Load the dataset and split it into training and testing sets
import pandas as pd 
dataset=pd.read_csv("bj_housing.csv")
dataset.head()

In [19]:
X = dataset.iloc[:,[0,2,3,4,5,6]].values
y = dataset.iloc[:,1].values
print(X)
print(y)

[[ 128    3    1    1 2004   21]
 [  68    1    2    1 2000    6]
 [ 125    3    2    0 2003    5]
 ...
 [  61    2    1    0 1986   16]
 [  87    3    1    1 1960    5]
 [  54    2    1    1 1986    6]]
[370 330 355 ... 240 350 180]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Define the ANN regressor model
model = MLPRegressor(hidden_layer_sizes=(100, 50), activation='relu', solver='adam', max_iter=1000)

# Train the model on the training data
model.fit(X_train, y_train)

# Use the trained model to make predictions on the testing data
y_pred = model.predict(X_test)

# Evaluate the performance of the model using mean squared error
mse = mean_squared_error(y_test, y_pred)
print(f"Mean squared error: {mse}")

In [ ]:
model.get_params

In [ ]:
# Import necessary libraries
import tensorflow as tf
import numpy as np
# Define the architecture of the ANN regressor model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1)
])

# Compile the model
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Train the model on the training data
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2)

# Use the trained model to make predictions on the testing data
y_pred = model.predict(X_test)

# Evaluate the performance of the model using mean squared error
mse = np.mean((y_test - y_pred.flatten())**2)
print(f"Mean squared error: {mse}")

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                multiple                  896       
_________________________________________________________________
dense_1 (Dense)              multiple                  8256      
_________________________________________________________________
dense_2 (Dense)              multiple                  65        
Total params: 9,217
Trainable params: 9,217
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#from ann_visualizer.visualize import ann_viz

#ann_viz(model, title="My first neural network2")

In [21]:
int(model.predict([[ 120,    4,    1,    1, 2020,   31]]))

489